### ISSUE TITLE
sqlite-net-sqlcipher 1.7.302-beta compilator error: missing constructor for providing encryption key

### ISSUE THREAD

**Issue by sasivishnu** [praeclarum/sqlite-net#880]
Hi, First of all, thanks @praeclarum and @ericsink for this awesome tool. 

After updating to sqlite-net-cipher to 1.7.302 beta version, I am getting compilation error, `SQLiteConnection() does not contain constructor that takes 4 arguments`.

I checked the code and surprised to find all the constructors relating to supplying `encryption` key is gone. I can find those constructor methods in v1.6.292 though (https://github.com/praeclarum/sqlite-net/blob/v1.6.292/src/SQLite.cs#L2187)

Is it by mistake or 1.7.302 beta is not yet ready for consumption?

Thanks again,

**Comment by hardikphd** [comment]
@praeclarum Same issue exists in latest 1.6.292, We are using this parameter to pass encryption key.
Do we have alternative?

**Comment by MattVon** [comment]
Please refer to the solution to your problem here: https://github.com/praeclarum/sqlite-net/issues/875#issuecomment-533482364

**Comment by hardikphd** [comment]
Thanks @MattVon , It worked for me!!!
